#!/bin/bash -e

#This a Slurm script for the single-cell pipeline fixed RNA

#SBATCH --job-name=cellranger-multi
#SBATCH --account=vuw03876
#SBATCH --time=12:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=128GB
#SBATCH --output=/nesi/nobackup/vuw03876/single-cell/sc1yr_multi%j.out
#SBATCH --error=/nesi/nobackup/vuw03876/single-cell/sc1yr_multi%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-type=TIME_LIMIT_80
#SBATCH --mail-user=email

#module loading

module load CellRanger/7.1.0

#Define input and output directories and variables

cd /nesi/nobackup/vuw03876/single-cell

#run cell ranger count
cellranger multi --id=sc1yr_count_test_singlesample --csv=/nesi/nobackup/vuw03876/single-cell/sc1yr-config-test.csv
