#!/bin/bash -e

#This a Slurm script for the single-cell pipeline

#SBATCH --job-name=fastqc
#SBATCH --account=vuw03876
#SBATCH --time=8:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem=20GB
#SBATCH --output=/nesi/nobackup/vuw03876/single-cell/file-download%j.out
#SBATCH --error=/nesi/nobackup/vuw03876/single-cell/file-download%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-type=TIME_LIMIT_80
#SBATCH --mail-user=email
BASE_PATH="/nesi/nobackup/vuw03876/single-cell"

cd $BASE_PATH/data/SCZ13461-Trimmed/fastq_merged

module purge

#module loading
module load FastQC/0.12.1
module load CellRanger/7.1.0

#Define input and output directories and variables

INPUT="$BASE_PATH/data/SCZ13461-Trimmed/fastq_merged"
OUTPUT="$BASE_PATH/results"
GENOME="$BASE_PATH/genomes/"

#make required directories

#mkdir $OUTPUT/fastqc_results

#Quality Control
fastqc -o $OUTPUT/fastqc_results $INPUT/*.fastq.gz

#decompress reference genome
cd $GENOME
tar -zxvf refdata-gex-GRCm39-2024-A.tar.gz

#
